### ISSUE TITLE
Local web 8080 always redirected to https://app.systeminit.com/

### ISSUE THREAD

**Issue by snowsky** [systeminit/si#4741]
### What happened?

Thanks for the recent open sourced decision. I gave the local dev a test and it is up successfully. When I tried to access http://localhost:8080, the page is redirected to https://app.systeminit.com/. Is this expected?

### How can we reproduce this?

As above.

### Operating system

Linux

### Architecture

x86_64 / amd64

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stack72** [comment]
Hi @snowsky 

Thanks for opening the issue here - the TLDR is that we have a centralised authentication mechanism that will try to take you to your default workspace

Currently when you created an account you were given a production workspace which is the default. So to access your local instance go to https://auth.systeminit.com/workspaces and choose the localhost variant of it

That should get you through to it. Let me know if this doesn't work for you

Paul

**Comment by snowsky** [comment]
Thanks it works, I deleted the old instance and recreated a workspace and chose local instance. :+1:

**Comment by stack72** [comment]
Great news @snowsky - let us know if you need anything :)
